### ISSUE TITLE
ERROR: DB incompatible with selected queries/identity.

### ISSUE THREAD

**Issue by matthpich** [knights-lab/BURST#12]
Hi BURSTers,
Do you know how to solve this issue:
"ERROR: DB incompatible with selected queries/identity."
Many thanks for your help!

**Comment by GabeAl** [comment]
BURSTers. I like it. 😁


It basically means that the database you're using was made to only handle
queries of a certain length (like maybe length 300 but depends on how the
DB was made), but some of your query DNA sequences you're trying to align
are longer than this.

Usually the identity thing doesn't apply because most folks align at
typical identies of 94 to 99% similarity.

Hope that helps!
