### ISSUE TITLE
Speed slower than expected

### ISSUE THREAD

**Issue by theo-allnutt-bioinformatics** [knights-lab/BURST#18]
Hi, 

I have a 1M read test file I am running against a large DB: 101 Gb .edx and 17 Gb .acx files. The search took approximately 2 hours with 24 cpus (Intel Xeon 2.6 GHz). This was much slower than I expected, with Ublast on the same machine and files running in about 15 minutes. However, I find Burst is more accurate than Ublast. Is there a reccommended way to speed up Burst, or is this DB just too large.

Thanks,

Theo

**Comment by GabeAl** [comment]
Thanks for trying it out.

Short answer - yes!

But first, I am confused why your acx file is much smaller than your edx
file; usually it is the opposite. But assuming it is the opposite, keep in
mind most of the time spent in a case like this is loading in the database.

The main trick is, BURST scales highly *sub-linearly* with number of input
queries! While it may take a painfully long 2 hours on just 1M sequences,
it may only take 3 hours for 10M sequences, and 5 hours for 100M sequences
(depending on their characteristics, disk speed, etc). The speed per
sequence goes up with more sequences in your input file! Of course this is
limited by your available RAM, so there are practical limits on the speedup
using this approach. But with sufficient RAM, I have observed burst running
at well over 1M queries per minute on my system.

BURST was designed to accept input from SHI7, which is my QC program that
supports a "combined_seqs.fna" format similar to QIIME1. Because of this,
multiple (shallow) samples may be multiplexed into one large file.

The more queries you give it in a single run:
- the shorter the DB load time will be relative to the actual alignment time
- the more redundancy BURST can find between queries to speed up the matrix
calculations

BURST's main acceleration technique is to take advantage of redundancies
among queries using various approaches.

It should also have no false negative or false positive alignments under
your alignment identity, so its accuracy should indeed be perfect, unlike
aligners such as Ublast which use heuristics to speed up the alignments.

Cheerio,
Gabe

**Comment by theo-allnutt-bioinformatics** [comment]
Typo - acx / edx the other way around. I changed my search from 'ANY' to 'FORAGE' and --skipambig, and it ran in minutes, so the DB loading was not a problem, but I take your point about concatenating inputs. Question. if you utilise redundancies between input samples doesn't that affect their independance, or doe sit literally only affect the algroithm speed and not actual accuracy or counts?

Thanks.

**Comment by theo-allnutt-bioinformatics** [comment]
Also - Is it possible for you to add an optin to output non-aligned reads? This would be very useful for sequential 'filtering' alignments, e.g. to different databases. Thanks.

**Comment by GabeAl** [comment]
Hi Theo,

In general, ANY should not be used for general alignments -- and it
definitely shouldn't be slower than FORAGE!

It could be the --skipambig (-sa) flag that helped most, as it may have
been spending time on sequences with a lot of ambiguous bases.

Also note that database load speed depends on whether the same database was
loaded before on the same computer recently. If so, loading time on
second run is much reduced!

No effect on accuracy or counts with more sequences.

Cheerio,
Gabe
