### ISSUE TITLE
Burst missing alignments that blast finds

### ISSUE THREAD

**Issue by theo-allnutt-bioinformatics** [knights-lab/BURST#22]
Hi, 

I am using v0.99.8 special edition [PT2.5]; DB15 version.

The issue is that burst fails to find good alignments to a database, but it will find the alignments to the equivalent fasta file. Blast (current version) finds the expected alignments in both cases.

To make the db:

burst_linux_DB15 -r coli.fa -o coli.edx -a coli.acx -d DNA 151 -i 0.95 -t 12 -s 1500 -n

to search the db, this give zero results:

burst_linux_DB15 -r ~/db/burst/coli.edx -a ~/db/burst/coli.acx -q 102leish_test.fa -o burst_leish_test2 -fr -w -m FORAGE -i 0.97 -t 8 -n --skipambig

To search a fasta also containing E. coli, gives expected results:

burst_linux_DB15 -r k12.fna -q 102leish_test.fa -o burst_leish_test -fr -w -m FORAGE -i 0.97 -t 8 -n --skipambig

All the files are in the link below. I have included the test db fasta file, not the edx or acx due to their size.

https://drive.google.com/open?id=1ig8WjbR3vRRh5gcthoHdOjOoXpaaoBsh

I hope this is not a serious issue, but it seems very odd to me that burst should behave so differently when using a db file compared to a fasta reference. I was hopignt o use burst as a replacement for kraken2 and that it might be more accurate but I have had to put this benchmarking on hold until this issue is resolved.

Thanks for your help,

Theo

**Comment by GabeAl** [comment]
Hi Theo,

There are a number of problems here. Let me do my best to help.

1. Please remember to ensure that all fasta files given to burst are
*linearized*. The fa for E coli spans multiple lines per sequence,
including the line-break character. This is not compatible with BURST (and
may also produce spurious outputs regarding non-printing characters, etc).
I should check for this in the future and throw an warning rather than
continuing with the file.

2. For a single bacterial genome, it is much more desirable to use the DB12
version than the DB15 version. The DB15 version has overhead designed to
cope with very large databases, not single bacterial genomes. Most of the
time is wasted reading a huge database header, so this is not a good
candidate for a benchmark involving speed.

3. Your alignment expectations are invalid. BLAST returns local alignments,
BURST does not. This is very much by design. Consider the following:
    a. Look at column 4 in the blast output. It shows that the alignment
length is 30 for most of the alignments found. This is a worthless
alignment. BURST only reports alignments that are *full length* of the
query, and calculates percent identity based on that.
    b. Many of the longer alignments in the blast file are lower identity
than the identity cutoff you chose. So they are also invalid.
    c. When you run BURST with a lower identity threshold (like 0.95), you
will get alignments -- more meaningful ones than the average BLAST hit.

4. Your query sequences seem to contain garbage sequence on the ends.
Consider a proper QC program such as SHI7 to remove adaptors and
contaminants.

5. Combining these suggestions together:
- Linearize your starting reference fasta files.
- Make a single-genome database with BURST12 rather than BURST15 to save
time/RAM/space
- properly filter the BLAST results for end-to-end alignments (or failing
that, for alignments with length >= identity & pid >= identity, then
compute end-to-end identity by multiplying the two as decimals, e.g. 0.99
query cover * 0.97 identity = 0.96 total alignment identity)
- run your queries through proper QC, don't convert directly from fastq

Hope this helps!
Gabe

**Comment by theo-allnutt-bioinformatics** [comment]
Thanks, yes that clears it up.

**Comment by GabeAl** [comment]
@theo-allnutt-bioinformatics 

This returns 43 full-length alignments with identity > ~93.5%:
```
linfasta k12.fna k12.lin.fna
burst_linux_DB12 -r k12.lin.fna -o k12.edx -a k12.acx -d DNA 152 -i 0.935 -t 8 -s 1500
burst_linux_DB12 -r k12.edx -a k12.acx -q 102leish_test.fa -o k12.b6 -fr -m FORAGE -i 0.935 -t 8 -sa
```
...and this returns 205 full-length alignments with identity > ~93.5%:
```
linfasta coli.fa coli.lin.fna
burst_linux_DB12 -r coli.lin.fna -o coli.edx -a coli.acx -d DNA 152 -i 0.935 -t 8 -s 1500
burst_linux_DB12 -r coli.edx -a coli.acx -q 102leish_test.fa -o coli.b6 -fr -m FORAGE -i 0.935 -t 8 -sa
```

Of course feel free to lower the identity threshold further (but then to use the .acx, you'll have to enable '-hr' during alignment). 

Cheerio,
Gabe
