### ISSUE TITLE
Complexity filter

### ISSUE THREAD

**Issue by theo-allnutt-bioinformatics** [knights-lab/BURST#23]
Is it possible to add a low complexity filter to Burst?

Thanks,

Theo

**Comment by GabeAl** [comment]
This is a good idea, Theo.

I would probably add it to SHI7 rather than burst, as it is a read
filtering / QC step rather than part of alignment (even though some tools
such as BLAST integrate this into the aligner).

I'm just not sure complexity masking is a good idea for all (or even most
semi-global) cases though. For instance, in end-to-end query alignment, one
often wants to aggregate alignments after a run to calculate coverage of
the reference genome(s). If low complexity reads were dropped, this may not
be possible as gaps would be introduced in low complexity regions, and if
filtering is also applied to the reference genomes, their length and class
distribution would be biased as some families are naturally more complex
throughout their genome than others. Also, for taxonomy assignment, they
may still be of (limited) use as they can contribute to LCA and Bayesian
redistribution (even at less informative broad taxonomic levels).

What was the use case you had in mind?

Thanks,
Gabe

**Comment by theo-allnutt-bioinformatics** [comment]
Hi Gabe,

what I was thinking was for more grossly simple sequences. Despite normal QC, I still see, e.g. 150 bp of 'A's interspersed with very few other bases. Also long SSRs may cover complete 150bp reads.

Thanks,

Theo
