### ISSUE TITLE
ERROR When Creating a BURST Database out of the NCBI Representative Genomes

### ISSUE THREAD

**Issue by zhuojinh** [knights-lab/BURST#27]
I am new to Burst and I was trying to build the database. When I follow the step 3 (Lingenome without stripping anything).  `lingenome . Rep94.fasta FILENAME`
There was an error showing that "syntax error near unexpected token `newline'". 
Could you help me with this? Thanks!!!

**Comment by GabeAl** [comment]
Hi there!

This sounds like a problem with a script that contains newlines that aren't terminated in the unix "\n", rather than something with lingenome or burst itself. To narrow down what is causing this, could you answer the following:

What environment are you using? What version of lingenome? What happens when you try running lingenome without any arguments?

Cheerio,
Gabe

**Comment by zhuojinh** [comment]
I am using Ubuntu 20.04, if I run burst/lingenome without any argument or only -h
`./burst_linux_DB15`   
`./burst_linux_DB15 -h` 
`./lingenome`
`./lingenome -h`
give me the same error
./lingenome: line 6: syntax error near unexpected token `newline'
./lingenome: line 6: `<!DOCTYPE html>'

**Comment by GabeAl** [comment]
Wow, you're saying when you run `./burst_linux_DB15 -h` you get a message saying:
./lingenome: line 6: syntax error near unexpected token newline' ./lingenome: line 6: ?

If so, I'm afraid there must be something amiss with your system or configuration, because the burst binary has no knowledge of or reference to the lingenome program. Nor should any of them contain free text or newlines, as they are machine language, not scripting language like R or Python. Where did you download them?

Are you using the binaries from the releases page? It looks like you may be trying to execute a text file. Are you trying to run the source code? Or maybe your browser downloaded an error page instead of the actual program? What is the filesize of these programs on your computer? 

Can you upload the programs to this thread so I can inspect them? I would very much like to know more details to prevent such a mysterious situation from happening to anyone else. This is the first time I've heard of this situation.

**Comment by zhuojinh** [comment]
It seems to be my system setting fault, sorry about that！
