### ISSUE TITLE
Automate DB creation

### ISSUE THREAD

**Issue by danknights** [knights-lab/BURST#6]
Would be nice to have BURST do it's own acc-->acx and edb-->edx conversion behind the scenes for DB creation, rather than requiring three steps.

**Comment by GabeAl** [comment]
Agreed. And also lose the distinction between the "12" and "15" formats. And also the distinction between database and accelerator entirely -- who would want to use this thing without the SPEED?

Basically the DB stuff needs retooling. But it's always gotten the backburner thus far because so many awesome things in the core get bumped in priority. Definitely on the radar 👍
